api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/plugins/checklist/api/Entity'
            - '%kernel.project_dir%/plugins/reference/api/Entity'
    path_segment_name_generator: App\Operation\EntityPathSegmentNameGenerator
