api_platform:
    formats:
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        jsonapi:  ['application/vnd.api+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        yaml:     ['application/x-yaml']
        csv:      ['text/csv']
        html:     ['text/html']
    mapping:
        paths:
            - '%kernel.project_dir%/src/api/Entity'
            - '%kernel.project_dir%/plugins/checklist/api/Entity'
            - '%kernel.project_dir%/plugins/reference/api/Entity'
            - '%kernel.project_dir%/plugins/collection/api/Entity'
            - '%kernel.project_dir%/plugins/crowdSource/api/Entity'
            - '%kernel.project_dir%/plugins/exsiccati/api/Entity'
            - '%kernel.project_dir%/plugins/glossary/api/Entity'
            - '%kernel.project_dir%/plugins/imageProcessor/api/Entity'
            - '%kernel.project_dir%/plugins/key/api/Entity'
            - '%kernel.project_dir%/plugins/media/api/Entity'
            - '%kernel.project_dir%/plugins/occurrence/api/Entity'
            - '%kernel.project_dir%/plugins/occurrenceAssociation/api/Entity'
            - '%kernel.project_dir%/plugins/occurrenceComment/api/Entity'
            - '%kernel.project_dir%/plugins/occurrenceDataset/api/Entity'
            - '%kernel.project_dir%/plugins/occurrenceGenetic/api/Entity'
            - '%kernel.project_dir%/plugins/occurrenceLoan/api/Entity'
            - '%kernel.project_dir%/plugins/taxa/api/Entity'
            - '%kernel.project_dir%/plugins/traits/api/Entity'
    path_segment_name_generator: Core\Operation\EntityPathSegmentNameGenerator
