parameters:
    env(DATABASE_URL): ''
    env(DATABASE_DRIVER): ''
    env(DATABASE_SERVER_VERSION): ''

doctrine:
    dbal:
        driver: '%env(resolve:DATABASE_DRIVER)%'
        server_version: '%env(resolve:DATABASE_SERVER_VERSION)%'
        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
            _text: string
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Checklist:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/plugins/checklist/api/Entity'
                prefix: 'Checklist\Entity'
                alias: Checklist
            Reference:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/plugins/reference/api/Entity'
                prefix: 'Reference\Entity'
                alias: Reference
