version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    working_dir: /symbiota2
    volumes:
      - ./:/symbiota2
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - mariadb
      - postgres
    ports:
      - 80:80

  php:
    build: ./docker/php-fpm
    container_name: php
    restart: always
    working_dir: /symbiota2
    volumes:
      - ./:/symbiota2
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    depends_on:
      - mysql
      - mariadb
      - postgres

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symbiota2
    ports:
      - 3308:3306

  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symbiota2
    ports:
      - 3310:3306

  postgres:
    build: ./docker/postgis
    container_name: postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: symbiota2
    ports:
      - 5434:5432

  adminer:
    image: adminer:4.7
    container_name: adminer
    restart: always
    depends_on:
      - mysql
      - mariadb
      - postgres
    ports:
      - 8080:8080

  elk:
    image: sebp/elk
    container_name: elk
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
